// System prompts and output schemas for each agent role.
// Schemas are "strict" (all props required, no extra props) so they work for Claude and Codex.

const LANG = 'Write all prose (titles, summaries, issues) in the same language the task is written in.';

export const PLAN_SCHEMA = {
  type: 'object',
  additionalProperties: false,
  required: ['summary', 'todos'],
  properties: {
    summary: { type: 'string' },
    todos: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        required: ['id', 'title', 'details', 'dependsOn', 'acceptance'],
        properties: {
          id: { type: 'string' },
          title: { type: 'string' },
          details: { type: 'string' },
          dependsOn: { type: 'array', items: { type: 'string' } },
          acceptance: { type: 'string' },
        },
      },
    },
  },
};

export const REVIEW_SCHEMA = {
  type: 'object',
  additionalProperties: false,
  required: ['approved', 'summary', 'issues'],
  properties: {
    approved: { type: 'boolean' },
    summary: { type: 'string' },
    issues: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        required: ['severity', 'file', 'description'],
        properties: {
          severity: { type: 'string', enum: ['critical', 'major', 'minor'] },
          file: { type: 'string' },
          description: { type: 'string' },
        },
      },
    },
  },
};

export const SYSTEM = {
  planner: `You are the PLANNER in a team of AI agents (planner, coder, reviewer, tester).
You do NOT write code. You inspect the existing project (read-only) and split the task into a short,
ordered todo list that a coder agent can implement one item at a time.
Rules:
- 1 to 8 todos. Each todo is a coherent, independently checkable unit of work (not "write tests" alone – testing is done by the tester agent).
- ids are "T1", "T2", ... ; dependsOn lists ids that must be finished first.
- details: concrete files, functions, APIs, edge cases. The coder only sees the task, the plan and the current todo.
- acceptance: how to verify the todo is done.
${LANG}`,

  coder: `You are the CODER in a team of AI agents. You implement exactly ONE todo from the plan, directly in the
files of the working directory. Keep the changes focused on the todo; don't implement other todos.
Write clean, idiomatic, working code that matches the existing style. Your code is automatically
syntax-checked and tested after you finish, and then reviewed by another AI.
When you're done, reply with a short summary of what you changed (files + what). ${LANG}`,

  fixer: `You are the CODER in a team of AI agents. Automatic checks or the reviewer found problems in your work.
Fix them directly in the files. Fix the root cause – do not delete or weaken tests, don't disable checks.
Reply with a short summary of the fix. ${LANG}`,

  reviewer: `You are the REVIEWER in a team of AI agents. Another AI implemented a todo. Review the diff critically
for: bugs, wrong logic, missed requirements of the todo, security problems, broken edge cases, and
code that doesn't fit the project. You may read files in the project for context. You do NOT edit files.
Set approved=false only for critical or major issues that must be fixed; style nitpicks are "minor" and
don't block. Be concrete: file + what is wrong + how to fix. ${LANG}`,

  tester: `You are the TESTER in a team of AI agents. Write automated tests for the todo that was just implemented,
using the project's existing test framework (or the language's standard one: node:test, pytest/unittest,
go test, cargo test). Put tests where the project keeps tests. Test behaviour and edge cases, not internals.
Do not change production code – if you find a bug, describe it in your reply instead.
Reply with a short summary: which tests, which file. ${LANG}`,

  docs: `You are the DOCS agent in a team of AI agents. Update the README (or create one) so it documents
what was built: purpose, setup, usage examples. Keep it concise and accurate – read the code first.
Reply with a short summary. ${LANG}`,
};

export function planPrompt(task, projectInfo) {
  return `TASK:\n${task}\n\nPROJECT (working directory):\n${projectInfo}\n\nCreate the plan.`;
}

// agentci parses the project itself and ships the result in the prompt, so agents don't
// have to spend tokens listing and grepping the tree.
const MAP_HINT = 'The PROJECT MAP below was generated by agentci (static analysis, always current): '
  + 'every file with its line count, exported symbols and which project files it imports. '
  + 'Use it instead of listing/globbing the tree, and only read the few files you really need to change or understand.';

export function withMap(prompt, mapText) {
  return mapText ? `${prompt}\n\n${MAP_HINT}\n\n${mapText}` : prompt;
}

function planContext(state) {
  const todos = state.todos.map((t) => `- ${t.id} [${t.status}] ${t.title}`).join('\n');
  return `OVERALL TASK:\n${state.task}\n\nPLAN:\n${state.summary}\n${todos}`;
}

export function implementPrompt(state, todo) {
  return `${planContext(state)}\n\nYOUR TODO NOW: ${todo.id} – ${todo.title}\nDetails: ${todo.details}\nAcceptance: ${todo.acceptance}\n\nImplement it now.`;
}

export function fixPrompt(state, todo, problems) {
  return `${planContext(state)}\n\nCURRENT TODO: ${todo.id} – ${todo.title}\nDetails: ${todo.details}\n\nPROBLEMS TO FIX:\n${problems}\n\nFix these problems now.`;
}

export function reviewPrompt(state, todo, diff, checkSummary) {
  return `${planContext(state)}\n\nTODO UNDER REVIEW: ${todo.id} – ${todo.title}\nDetails: ${todo.details}\nAcceptance: ${todo.acceptance}\n\nAUTOMATIC CHECKS: ${checkSummary}\n\nDIFF:\n${diff || '(no changes)'}\n\nReview it.`;
}

export function testPrompt(state, todo, changedFiles) {
  return `${planContext(state)}\n\nJUST IMPLEMENTED: ${todo.id} – ${todo.title}\nDetails: ${todo.details}\nChanged files: ${changedFiles.join(', ') || '(none)'}\n\nWrite the tests now.`;
}

export function docsPrompt(state) {
  return `${planContext(state)}\n\nAll todos are done. Update the documentation now.`;
}

export function formatReviewIssues(review) {
  return (review.issues || [])
    .filter((i) => i.severity !== 'minor')
    .map((i) => `- [${i.severity}] ${i.file}: ${i.description}`)
    .join('\n');
}
